// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var $, $async, $show, $watch, CND, FS, OS, PATH, SP, alert, badge, debug, defer, echo, help, info, jr, log, rpr, test, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'STEAMPIPES/TESTS/NJS-STREAMS-AND-FILES';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  //...........................................................................................................
  PATH = require('path');

  FS = require('fs');

  OS = require('os');

  test = require('guy-test');

  ({jr} = CND);

  //...........................................................................................................
  SP = require('../..');

  ({$, $async, $watch, $show} = SP.export());

  defer = setImmediate;

  //-----------------------------------------------------------------------------------------------------------
  this["write to file sync"] = async function(T, done) {
    /* TAINT use proper tmpfile */
    var error, matcher, path, probe;
    path = '/tmp/steampipes-testfile.txt';
    if (FS.existsSync(path)) {
      FS.unlinkSync(path);
    }
    probe = "just a bunch of words really".split(/\s+/);
    matcher = null;
    error = null;
    await T.perform(probe, matcher, error, function() {
      return new Promise(function(resolve, reject) {
        var R, pipeline, source;
        R = [];
        source = probe;
        //.......................................................................................................
        pipeline = [];
        pipeline.push(source);
        pipeline.push($(function(d, send) {
          return send(d + '\n');
        }));
        pipeline.push($watch(function(d) {
          return info('mainline', jr(d));
        }));
        // pipeline.push SP.tee_write_to_file path
        pipeline.push(SP.tee_write_to_file_sync(path));
        pipeline.push(SP.$drain(function(sink) {
          var result;
          matcher = sink.join('');
          if (FS.existsSync(path)) {
            result = FS.readFileSync(path, {
              encoding: 'utf-8'
            });
          } else {
            result = null;
          }
          // urge 'µ77655', ( jr result ), ( jr matcher )
          T.eq(result, matcher);
          help('ok');
          return resolve(null);
        }));
        SP.pull(...pipeline);
        return null;
      });
    });
    //.........................................................................................................
    done();
    return null;
  };

  //###########################################################################################################
  if (module.parent == null) {
    test(this, {
      'timeout': 30000
    });
  }

}).call(this);

//# sourceMappingURL=njs-streams-and-files.test.js.map
